### ISSUE TITLE
Error: Cannot find module 'inherit'

### ISSUE THREAD

**Issue by imjacobclark** [jkphl/svg-sprite#137]
Encountered the issue `Error: Cannot find module 'inherit'` within our CI pipeline over the past two days.

Affecting version `1.2.17`

Full stacktrace:

```shell
module.js:339
    throw err;
    ^

Error: Cannot find module 'inherit'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/food/node_modules/svg-sprite/node_modules/svgo/node_modules/js-yaml/lib/js-yaml/exception.js:6:16)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

I believe this is related to: https://github.com/nodeca/js-yaml/pull/240

Raising this for visibility incase other people see this issue.

I believe the fix is to upgrade your version of svg-sprite.

**Comment by jkphl** [comment]
@imjacobclark Thanks for reporting this! You're right, the current version of *svg-sprite* should already feature the most recent version of *js-yaml* as a dependency. There seems to be a couple of other outdated dependencies at the moment though, I'll take care of them as soon as I find some minutes.

**Comment by imjacobclark** [comment]
Thanks for the reply @jkphl!

**Comment by jkphl** [comment]
@imjacobclark I just updated all dependencies and will hopefully push out a new release later today — FINALLY! — so I'll close this issue at this point.
