### ISSUE TITLE
--config failing

### ISSUE THREAD

**Issue by bfred-it** [jkphl/svg-sprite#183]
**Command**

```sh
svg-sprite --config config.json *.svg
```

**config.json**

```json
{
    "mode": {
        "symbol": true
    }
}
```

**stderr**

```log 
/usr/local/lib/node_modules/svg-sprite/bin/svg-sprite.js:231
		if ((render in this) && !argv[arg]
		               ^

TypeError: Cannot use 'in' operator to search for 'css' in undefined
    at /usr/local/lib/node_modules/svg-sprite/bin/svg-sprite.js:231:18
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-sprite/bin/svg-sprite.js:229:34)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-sprite/bin/svg-sprite.js:222:44)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Working commands**

```sh
svg-sprite *.svg
svg-sprite --symbol *.svg
```

**Comment by jkphl** [comment]
Please also provide the contents of your `config.json`. Thanks.

**Comment by bfred-it** [comment]
It's there

**Comment by jkphl** [comment]
Sorry, must have overseen it (only on my mobile phone atm)

**Comment by bfred-it** [comment]
No worries :)

**Comment by jkphl** [comment]
The problem was the shorthand definition of the `symbol` mode (by simply setting it to `true`). This needed to be expanded by the CLI script ... Thanks for reporting! :)

**Comment by bfred-it** [comment]
Makes sense! Thanks
