### ISSUE TITLE
"{}" is not a valid mode configuration

### ISSUE THREAD

**Issue by Johnius** [jkphl/svg-sprite#68]
I'm using
- elementary OS Luna
- Node v0.10.36
- Npm v1.4.28

To install svg-sprite I used `npm install -g svg-sprite`
Then I did `svg-sprite *.svg`

And got an error
```ShellSession
{ [ArgumentError: SVGSpriter.compile: "{}" is not a valid mode configuration] name: 'ArgumentError', errno: 1420362541 }

/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90
	Array.prototype.push.apply(this._spriter._shapes, shape.distribute());
	                                                        ^
TypeError: Cannot call method 'distribute' of undefined
    at EventEmitter.SVGSpriterQueue.remove (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90:58)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:544:30
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:184:3
    at Object.module.exports [as svgo] (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:80:3)
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:168:38
    at fn (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by jkphl** [comment]
@Johnius Please refer to the manual. You have to enable at least one valid `mode` to get a reasonable output (e.g. `--css`).

**Comment by Johnius** [comment]
I used the option `--css`. But still gets an error
```shellsession
/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90
	Array.prototype.push.apply(this._spriter._shapes, shape.distribute());
	                                                        ^
TypeError: Cannot call method 'distribute' of undefined
    at EventEmitter.SVGSpriterQueue.remove (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90:58)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:544:30
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:184:3
    at Object.module.exports [as svgo] (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:80:3)
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:168:38
    at fn (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by jkphl** [comment]
Did you also specify an output directory? Please try to run one of the [example commands](https://github.com/jkphl/svg-sprite/blob/master/docs/command-line.md#examples) and let me know if that works (and please always post the complete commands you run).

**Comment by Johnius** [comment]
I have used these commands from 
```

**Comment by Johnius** [comment]
I have used these [example commands](https://github.com/jkphl/svg-sprite/blob/master/docs/command-line.md#examples)
```shellsession
$ svg-sprite --css --css-render-css --css-example --dest=out assets/*.svg
$ svg-sprite -cD out --ccss --cx assets/*.svg
$ svg-sprite -cD out --cscss -p 10 assets/*.svg
```

I have two directories:
- *out* which is empty
- *assets* which have 3 svg files

But I still gets the same error
```shellsession
/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90
	Array.prototype.push.apply(this._spriter._shapes, shape.distribute());
	                                                        ^
TypeError: Cannot call method 'distribute' of undefined
    at EventEmitter.SVGSpriterQueue.remove (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90:58)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:544:30
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:184:3
    at Object.module.exports [as svgo] (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:80:3)
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:168:38
    at fn (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by jkphl** [comment]
Please try running `svg-sprite --css --dest=out *.svg` (with the argument order this way). There's a known issue with *yargs* not treating the boolean arguments correctly (`--css`). Does this work then?

**Comment by jkphl** [comment]
Also, please enable `--log=debug` and post the output.

**Comment by Johnius** [comment]
Debug mode show the real reason of the error.
```shellsession
$ svg-sprite --css --dest=out *.svg --log=debug                                                                                             8 ↵
2015-03-12 20:41:18 - debug: Started logging
2015-03-12 20:41:18 - debug: Prepared general options
2015-03-12 20:41:18 - debug: Prepared `shape` options
2015-03-12 20:41:18 - debug: Prepared `svg` options
2015-03-12 20:41:18 - debug: Prepared `transform` options
2015-03-12 20:41:18 - debug: Prepared `mode` options
2015-03-12 20:41:18 - debug: Prepared `variables` options
2015-03-12 20:41:18 - verbose: Initialized spriter configuration
2015-03-12 20:41:18 - debug: Created processing queue instance
2015-03-12 20:41:18 - info: Created spriter instance
2015-03-12 20:41:18 - debug: Added "facebook.svg" to processing queue
2015-03-12 20:41:18 - verbose: Added shape "facebook:regular"
2015-03-12 20:41:18 - debug: Added "google.svg" to processing queue
2015-03-12 20:41:18 - verbose: Added shape "google:regular"
2015-03-12 20:41:18 - debug: Added "twitter.svg" to processing queue
2015-03-12 20:41:18 - verbose: Added shape "twitter:regular"
2015-03-12 20:41:18 - debug: Optimized "facebook.svg" with SVGO (saved 206 Bytes / 22%)
2015-03-12 20:41:18 - error: Optimizing "google.svg" with SVGO failed with error "%s" TypeError: Cannot read property 'content' of undefined
    at Object.exports.fn (/usr/local/lib/node_modules/svg-sprite/node_modules/svgo/plugins/removeUnknownsAndDefaults.js:83:24)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo/plugins.js:61:45
    at Array.filter (native)
    at monkeys (/usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo/plugins.js:46:39)
    at perItem (/usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo/plugins.js:81:12)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo/plugins.js:18:24
    at Array.forEach (native)
    at module.exports (/usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo/plugins.js:14:13)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo.js:43:21
    at Object.sax.onend (/usr/local/lib/node_modules/svg-sprite/node_modules/svgo/lib/svgo/svg2js.js:127:9)

/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90
	Array.prototype.push.apply(this._spriter._shapes, shape.distribute());
	                                                        ^
TypeError: Cannot call method 'distribute' of undefined
    at EventEmitter.SVGSpriterQueue.remove (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/queue.js:90:58)
    at /usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:544:30
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:184:3
    at Object.module.exports [as svgo] (/usr/local/lib/node_modules/svg-sprite/lib/svg-sprite/transform/svgo.js:80:3)
    at /usr/local/lib/node_modules/svg-sprite/lib/svg-sprite.js:168:38
    at fn (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/usr/local/lib/node_modules/svg-sprite/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

I just deleted `google.svg` and it works now.
I can upload this svg file for further understanding the roots of the error.

**Comment by jkphl** [comment]
That would be good, thanks! Which version of SVGO are you running? Is it already the new 0.5.1?

**Comment by Johnius** [comment]
The reason of that error was just my mistake. I incorrectly downloaded SVG file from Wikimedia. It was HTML-file instead of SVG.

Now I downloaded it correctly and everything works fine.

**Comment by jkphl** [comment]
Ah ok. Thanks for reporting. I'll consider improving the error message in this case though. ;)
